Translation and Documentation Pinning
wpilibsuite/dev-ops pull request #6
Opened 2021-06-25 17:14 UTC by Daltz333

Details the process used when tagging and releasing documentation/translations.

2021-06-25 17:17 UTC, AustinShalit requested changes

2021-06-25 17:17 UTC, AustinShalit commented on docs/release_processes/translation-documentation-pinning.md
> +Reference: ``/latest/`` is the "bleeding edge" branch of the docs. Accessible from [https://docs.wpilib.org/en/latest/](https://docs.wpilib.org/en/latest/) and ``/stable/`` is the "year-to-year" vers
```suggestion
Reference: ``/latest/`` is the "leading edge" branch of the docs. Accessible from [https://docs.wpilib.org/en/latest/](https://docs.wpilib.org/en/latest/) and ``/stable/`` is the "year-to-year" version of the docs. This is accessible from [https://docs.wpilib.org/en/stable/](https://docs.wpilib.org/en/stable/)
```

2021-06-25 17:17 UTC, AustinShalit commented on docs/release_processes/translation-documentation-pinning.md
> +- Translation and Documentation ``/latest/`` and ``/stable`` are at an equal point in history. This allows us to make "bleeding" edge changes to documentation and translations. The benefit of this, i
```suggestion
- Translation and Documentation ``/latest/`` and ``/stable`` are at an equal point in history. This allows us to make "leading" edge changes to documentation and translations. The benefit of this, is making it immediately live on both versions of the site.
```

2021-06-25 17:17 UTC, AustinShalit commented on docs/release_processes/translation-documentation-pinning.md
> +Last Updated: 6/25/2021
```suggestion
```

Git history handles this.

2021-06-25 17:17 UTC, AustinShalit commented on docs/release_processes/translation-documentation-pinning.md
> +# Documentation & Translation Pinning
```suggestion
# Documentation
```

What do you think of just calling this documentation?

2021-07-17 22:39 UTC, FeliciaAKelley approved these changes

2021-07-21 03:13 UTC, AustinShalit approved these changes

2021-07-21 03:14 UTC, merged